"""GraphQL schema for SoroScan API using Strawberry."""

from __future__ import annotations

import base64
from datetime import datetime
from enum import Enum
from typing import AsyncGenerator, List, Optional

import strawberry
import strawberry_django
from channels.layers import get_channel_layer
from django.db.models import Case, Count, IntegerField, Q, Value, When
from django.utils import timezone
from strawberry import auto
from strawberry.types import Info

from .cache_utils import get_or_set_json, query_cache_ttl, stable_cache_key
from .models import (
    CallGraph,
    ContractDependency,
    ContractEvent,
    ContractInvocation,
    ContractMetadata,
    Notification,
    TrackedContract,
    WebhookDeliveryLog,
)
from .services.timeline import build_timeline


def _get_authenticated_user(info: Info):
    """Safely extract authenticated user from context."""
    if info.context is None:
        return None
    if not hasattr(info.context, "request"):
        return None
    request = info.context.request
    if request is None:
        return None
    if not hasattr(request, "user"):
        return None
    user = request.user
    if user and hasattr(user, "is_authenticated") and user.is_authenticated:
        return user
    return None


# ---------------------------------------------------------------------------
# GraphQL types
# ---------------------------------------------------------------------------

@strawberry_django.type(TrackedContract)
class ContractType:
    id: auto
    contract_id: auto
    name: auto
    alias: auto
    description: auto
    is_active: auto
    last_event_at: auto
    deprecation_status: auto
    deprecation_reason: auto
    event_filter_type: auto
    event_filter_list: strawberry.scalars.JSON
    created_at: auto

    @strawberry.field
    def team_id(self) -> Optional[int]:
        tid = getattr(self, "team_id", None)
        return int(tid) if tid is not None else None

    @strawberry.field
    def organization_id(self) -> Optional[int]:
        oid = getattr(self, "organization_id", None)
        return int(oid) if oid is not None else None

    @strawberry.field
    def event_count(self) -> int:
        return self.events.count()

    @strawberry.field
    def warnings(self) -> list["WarningType"]:
        warning = self.deprecation_warning()
        if warning is None:
            return []
        return [
            WarningType(
                warning_type=warning["type"],
                message=warning["message"],
            )
        ]

    @strawberry.field
    def metadata(self) -> Optional["ContractMetadataType"]:
        try:
            m = self.contractmetadata
            return ContractMetadataType(
                name=m.name,
                description=m.description,
                tags=m.tags,
                documentation_url=m.documentation_url,
                github_repo=m.github_repo,
                team_email=m.team_email,
            )
        except ContractMetadata.DoesNotExist:
            return None


@strawberry.type
class WarningType:
    warning_type: str = strawberry.field(name="type")
    message: str


@strawberry.type
class ContractMetadataType:
    name: str
    description: str
    tags: strawberry.scalars.JSON
    documentation_url: str
    github_repo: str
    team_email: str


@strawberry_django.type(ContractEvent)
class EventType:
    id: auto
    event_type: auto
    payload: strawberry.scalars.JSON
    payload_hash: auto
    decoded_payload: Optional[strawberry.scalars.JSON]
    decoding_status: auto
    ledger: auto
    event_index: auto
    timestamp: auto
    tx_hash: auto
    schema_version: auto
    validation_status: auto
    signature_status: auto

    @strawberry.field
    def contract_id(self) -> str:
        return self.contract.contract_id

    @strawberry.field
    def contract_name(self) -> str:
        return self.contract.name


@strawberry_django.type(ContractInvocation)
class InvocationType:
    id: auto
    tx_hash: auto
    caller: auto
    function_name: auto
    parameters: strawberry.scalars.JSON
    result: strawberry.scalars.JSON
    ledger_sequence: auto
    created_at: auto

    @strawberry.field
    def contract_id(self) -> str:
        return self.contract.contract_id

    @strawberry.field
    def contract_name(self) -> str:
        return self.contract.name

    @strawberry.field
    def events(self) -> list[EventType]:
        """Nested events generated by this invocation."""
        return list(self.events.all())


@strawberry.type
class EventSearchResult:
    """A single event returned by the search resolver with a relevance score."""

    id: int
    contract_id: str
    event_type: str
    payload: strawberry.scalars.JSON
    ledger: int
    timestamp: datetime
    tx_hash: str
    relevance_score: float = 1.0


@strawberry.input
class EventFieldFilter:
    """Single field-level comparison filter."""

    eq: Optional[str] = None
    neq: Optional[str] = None
    gte: Optional[str] = None
    lte: Optional[str] = None
    gt: Optional[str] = None
    lt: Optional[str] = None
    contains: Optional[str] = None
    startswith: Optional[str] = None
    in_list: Optional[list[str]] = strawberry.field(
        name="in", default=None, description="Value must be one of these"
    )


@strawberry.input
class EventSearchQuery:
    """
    Input type for the ``searchEvents`` resolver.

    ``filters`` maps a dot-notation payload field path to a comparison object,
    e.g. ``{\"decodedPayload.to\": {eq: \"GXXX...\"}}``.
    """

    contract_id: Optional[str] = None
    payload_contains: Optional[str] = None
    event_type: Optional[str] = None
    filters: Optional[strawberry.scalars.JSON] = None
    first: int = 20
    after: Optional[str] = None


@strawberry.type
class PageInfo:
    has_next_page: bool
    end_cursor: Optional[str]


@strawberry.type
class EventEdge:
    node: EventType
    cursor: str


@strawberry.type
class EventConnection:
    edges: list[EventEdge]
    page_info: PageInfo
    total_count: int


@strawberry.type
class InvocationEdge:
    node: InvocationType
    cursor: str


@strawberry.type
class InvocationConnection:
    edges: list[InvocationEdge]
    page_info: PageInfo
    total_count: int


@strawberry.type
class ContractStats:
    contract_id: str
    name: str
    total_events: int
    unique_event_types: int
    last_activity: Optional[datetime]


@strawberry.type
class EventTypeCount:
    event_type: str
    count: int


@strawberry.enum
class TimelineBucketSize(Enum):
    FIVE_MINUTES = "FIVE_MINUTES"
    THIRTY_MINUTES = "THIRTY_MINUTES"
    ONE_HOUR = "ONE_HOUR"
    ONE_DAY = "ONE_DAY"


BUCKET_SECONDS_BY_SIZE = {
    TimelineBucketSize.FIVE_MINUTES: 300,
    TimelineBucketSize.THIRTY_MINUTES: 1800,
    TimelineBucketSize.ONE_HOUR: 3600,
    TimelineBucketSize.ONE_DAY: 86_400,
}


@strawberry.type
class EventTimelineGroup:
    start: datetime
    end: datetime
    event_count: int
    event_type_counts: list[EventTypeCount]
    events: list[EventType]


@strawberry.type
class EventTimelineResult:
    contract_id: str
    bucket_size: TimelineBucketSize
    since: datetime
    until: datetime
    total_events: int
    groups: list[EventTimelineGroup]


@strawberry.type
class SystemMetrics:
    events_indexed_today: int
    events_indexed_total: int
    webhook_success_rate: float
    avg_webhook_delivery_time: float
    active_contracts: int
    last_synced: Optional[datetime]
    db_status: str
    redis_status: str


@strawberry.type
class ErrorLog:
    id: int
    timestamp: datetime
    level: str
    message: str
    context: Optional[str]


# ---------------------------------------------------------------------------
# Contract Dependency Graph types (Issue #X)
# ---------------------------------------------------------------------------

@strawberry_django.type(ContractDependency)
class DependencyType:
    caller: ContractType
    callee: ContractType
    call_count: int
    first_call: datetime
    last_call: datetime


@strawberry_django.type(CallGraph)
class CallGraphType:
    contract: Optional[ContractType]
    graph_data: strawberry.scalars.JSON
    has_cycles: bool
    cycle_details: Optional[strawberry.scalars.JSON]
    computed_at: datetime


# ---------------------------------------------------------------------------
# Notification types (Issue #137)
# ---------------------------------------------------------------------------

@strawberry.enum
class NotificationTypeEnum(Enum):
    CONTRACT_PAUSED = "contract_paused"
    WEBHOOK_FAILURE = "webhook_failure"
    RATE_LIMIT = "rate_limit"
    SYSTEM = "system"
    ALERT = "alert"


@strawberry.type
class NotificationType:
    id: int
    notification_type: str
    title: str
    message: str
    link: str
    is_read: bool
    created_at: datetime


@strawberry.type
class Query:
    @strawberry.field
    def contracts(self, info: Info, is_active: Optional[bool] = None, alias: Optional[str] = None) -> list[ContractType]:
        """Get all tracked contracts. Optionally filter by alias substring. Sorted by alias when set."""
        qs = TrackedContract.objects.select_related("contractmetadata").all()
        user = _get_authenticated_user(info)
        if user:
            qs = qs.filter(
                Q(owner=user)
                | Q(team__memberships__user=user)
                | Q(organization__memberships__user=user)
            ).distinct()
        if is_active is not None:
            qs = qs.filter(is_active=is_active)
        if alias is not None:
            qs = qs.filter(alias__icontains=alias)
        # Sort: contracts with an alias come first (alphabetically), then by -created_at
        qs = qs.annotate(
            _has_alias=Case(
                When(alias="", then=Value(1)),
                default=Value(0),
                output_field=IntegerField(),
            )
        ).order_by("_has_alias", "alias", "-created_at")
        return qs

    @strawberry.field
    def contract(self, info: Info, contract_id: str) -> Optional[ContractType]:
        """Get a specific contract by ID."""
        user = _get_authenticated_user(info)
        if not user:
            try:
                return TrackedContract.objects.select_related("contractmetadata").get(contract_id=contract_id)
            except TrackedContract.DoesNotExist:
                return None
        try:
            return TrackedContract.objects.select_related("contractmetadata").get(
                contract_id=contract_id,
                owner=user,
            )
        except TrackedContract.DoesNotExist:
            return TrackedContract.objects.select_related("contractmetadata").filter(
                contract_id=contract_id,
            ).filter(
                Q(team__memberships__user=user) | Q(organization__memberships__user=user)
            ).first()

    @strawberry.field
    def contract_metadata(self, contract_id: str) -> Optional[ContractMetadataType]:
        """Get metadata for a specific contract by contract ID, or null if none exists."""
        try:
            m = ContractMetadata.objects.select_related("contract").get(contract__contract_id=contract_id)
            return ContractMetadataType(
                name=m.name,
                description=m.description,
                tags=m.tags,
                documentation_url=m.documentation_url,
                github_repo=m.github_repo,
                team_email=m.team_email,
            )
        except ContractMetadata.DoesNotExist:
            return None

    @strawberry.field
    def search_contracts(
        self,
        query: Optional[str] = None,
        tags: Optional[List[str]] = None,
        limit: int = 20,
    ) -> List[ContractType]:
        """Search contracts by metadata name/description and/or tags."""
        qs = TrackedContract.objects.select_related("contractmetadata").filter(
            contractmetadata__isnull=False
        )
        if query is not None:
            qs = qs.filter(
                Q(contractmetadata__name__icontains=query)
                | Q(contractmetadata__description__icontains=query)
            )
        if tags is not None:
            for tag in tags:
                qs = qs.filter(contractmetadata__tags__contains=[tag])
        qs = qs.order_by("contractmetadata__name")
        limit = min(limit, 100)
        return qs[:limit]

    @strawberry.field
    def events(
        self,
        contract_id: Optional[str] = None,
        event_type: Optional[str] = None,
        signature_status: Optional[str] = None,
        from_ledger: Optional[int] = None,
        to_ledger: Optional[int] = None,
        first: int = 20,
        after: Optional[str] = None,
        since: Optional[datetime] = None,
        until: Optional[datetime] = None,
    ) -> EventConnection:
        """Query events with cursor-based pagination and filtering.
        
        Ledger range filtering: if from_ledger or to_ledger is provided, both must be provided.
        Raises ValueError if from_ledger > to_ledger.
        """
        # Validate ledger range: either both or neither must be provided
        if (from_ledger is None) != (to_ledger is None):
            raise ValueError("Both from_ledger and to_ledger must be provided together, or neither")
        
        # Validate that from_ledger <= to_ledger
        if from_ledger is not None and to_ledger is not None and from_ledger > to_ledger:
            raise ValueError("from_ledger must be less than or equal to to_ledger")
        
        qs = ContractEvent.objects.select_related("contract").order_by("id")

        if contract_id:
            qs = qs.filter(contract__contract_id=contract_id)
        if event_type:
            qs = qs.filter(event_type=event_type)
        if signature_status is not None:
            normalized_signature_status = signature_status.lower()
            if normalized_signature_status in {"valid", "invalid", "missing"}:
                qs = qs.filter(signature_status=normalized_signature_status)
        if from_ledger is not None:
            qs = qs.filter(ledger__gte=from_ledger)
        if to_ledger is not None:
            qs = qs.filter(ledger__lte=to_ledger)
        if since:
            qs = qs.filter(timestamp__gte=since)
        if until:
            qs = qs.filter(timestamp__lte=until)

        total_count = qs.count()

        if after:
            try:
                decoded = base64.b64decode(after).decode("utf-8")
                after_id = int(decoded.split(":", 1)[1])
                qs = qs.filter(id__gt=after_id)
            except (ValueError, IndexError, UnicodeDecodeError):
                pass

        first = max(0, min(first, 100))

        if first == 0:
            return EventConnection(
                edges=[],
                page_info=PageInfo(has_next_page=qs.exists(), end_cursor=None),
                total_count=total_count,
            )

        items = list(qs[: first + 1])
        has_next = len(items) > first
        items = items[:first]

        edges = []
        for item in items:
            cursor = base64.b64encode(f"cursor:{item.id}".encode()).decode("utf-8")
            edges.append(EventEdge(node=item, cursor=cursor))

        return EventConnection(
            edges=edges,
            page_info=PageInfo(
                has_next_page=has_next,
                end_cursor=edges[-1].cursor if edges else None,
            ),
            total_count=total_count,
        )

    @strawberry.field
    def event(self, id: int) -> Optional[EventType]:
        """Get a specific event by ID."""
        try:
            return ContractEvent.objects.get(id=id)
        except ContractEvent.DoesNotExist:
            return None

    @strawberry.field
    def search_events(self, query: EventSearchQuery) -> list[EventSearchResult]:
        """
        Full-text and field-level search on contract event payloads.

        Supports:
        - ``contractId`` — filter by contract address
        - ``eventType`` — filter by event type
        - ``payloadContains`` — case-insensitive substring in JSON payload text
        - ``filters`` — dict mapping dot-notation field paths to comparison objects
          Supported operators per field: eq, neq, gte, lte, gt, lt, contains,
          startswith, in
        - Cursor-based pagination via ``first`` / ``after``
        """
        from django.db.models import TextField
        from django.db.models.functions import Cast

        qs = ContractEvent.objects.select_related("contract").all()

        if query.contract_id:
            qs = qs.filter(contract__contract_id=query.contract_id)
        if query.event_type:
            qs = qs.filter(event_type=query.event_type)

        if query.payload_contains:
            qs = qs.annotate(_pt=Cast("payload", output_field=TextField())).filter(
                _pt__icontains=query.payload_contains
            )

        if query.filters and isinstance(query.filters, dict):
            for field_path, ops in query.filters.items():
                if not isinstance(ops, dict):
                    continue
                orm_base = "payload__" + field_path.replace(".", "__")
                for op, val in ops.items():
                    if val is None:
                        continue
                    if op == "eq":
                        qs = qs.filter(**{orm_base: val})
                    elif op == "neq":
                        qs = qs.exclude(**{orm_base: val})
                    elif op in ("gte", "lte", "gt", "lt"):
                        qs = qs.filter(**{f"{orm_base}__{op}": val})
                    elif op == "contains":
                        qs = qs.filter(**{f"{orm_base}__icontains": val})
                    elif op == "startswith":
                        qs = qs.filter(**{f"{orm_base}__istartswith": val})
                    elif op in ("in", "in_list"):
                        values = val if isinstance(val, list) else [val]
                        qs = qs.filter(**{f"{orm_base}__in": values})

        # Cursor pagination (max 1000 per page)
        first = max(0, min(query.first, 1000))
        if query.after:
            try:
                decoded = base64.b64decode(query.after).decode()
                after_id = int(decoded.split(":", 1)[1])
                qs = qs.filter(id__gt=after_id)
            except (ValueError, IndexError, UnicodeDecodeError):
                pass

        qs = qs.order_by("id")
        items = list(qs[:first])

        return [
            EventSearchResult(
                id=e.id,
                contract_id=e.contract.contract_id,
                event_type=e.event_type,
                payload=e.payload,
                ledger=e.ledger,
                timestamp=e.timestamp,
                tx_hash=e.tx_hash,
                relevance_score=1.0,
            )
            for e in items
        ]

    @strawberry.field
    def contract_stats(self, contract_id: str) -> Optional[ContractStats]:
        """Get aggregate statistics for a contract."""
        key = stable_cache_key("gql_contract_stats", {"contract_id": contract_id})

        def _stats():
            try:
                contract = TrackedContract.objects.get(contract_id=contract_id)
            except TrackedContract.DoesNotExist:
                return None

            stats = contract.events.aggregate(
                total=Count("id"),
                unique_types=Count("event_type", distinct=True),
            )

            return ContractStats(
                contract_id=contract.contract_id,
                name=contract.name,
                total_events=stats["total"] or 0,
                unique_event_types=stats["unique_types"] or 0,
                last_activity=contract.last_event_at,
            )

        return get_or_set_json(key, query_cache_ttl(), _stats)

    @strawberry.field
    def dependencies_for_contract(self, contract_id: str) -> Optional[CallGraphType]:
        """
        Return the dependency DAG for a specific contract.
        If no contract-specific graph exists, returns the global graph.
        """
        # Try to find a contract-specific graph first
        graph = CallGraph.objects.filter(contract__contract_id=contract_id).first()
        if not graph:
            # Fall back to global graph (contract=None)
            graph = CallGraph.objects.filter(contract=None).first()

        return graph

    @strawberry.field
    def event_types(self, contract_id: str) -> list[str]:
        """Get all unique event types for a contract."""
        return list(
            ContractEvent.objects.filter(contract__contract_id=contract_id)
            .values_list("event_type", flat=True)
            .distinct()
        )

    @strawberry.field
    def event_timeline(
        self,
        contract_id: str,
        bucket_size: TimelineBucketSize = TimelineBucketSize.THIRTY_MINUTES,
        event_types: Optional[list[str]] = None,
        since: Optional[datetime] = None,
        until: Optional[datetime] = None,
        timezone: str = "UTC",
        limit_groups: int = 500,
        include_events: bool = True,
    ) -> EventTimelineResult:
        """Return grouped timeline data for contract event history."""
        bucket_seconds = BUCKET_SECONDS_BY_SIZE[bucket_size]
        timeline = build_timeline(
            contract_id=contract_id,
            bucket_seconds=bucket_seconds,
            event_types=event_types,
            since=since,
            until=until,
            timezone_name=timezone,
            limit_groups=limit_groups,
            include_events=include_events,
        )

        groups = [
            EventTimelineGroup(
                start=group.start,
                end=group.end,
                event_count=group.event_count,
                event_type_counts=[
                    EventTypeCount(event_type=item.event_type, count=item.count)
                    for item in group.event_type_counts
                ],
                events=group.events,
            )
            for group in timeline.groups
        ]

        return EventTimelineResult(
            contract_id=timeline.contract_id,
            bucket_size=bucket_size,
            since=timeline.since,
            until=timeline.until,
            total_events=timeline.total_events,
            groups=groups,
        )

    @strawberry.field
    def system_metrics(self, info: Info) -> SystemMetrics:
        """Get system-wide health and performance metrics."""
        user = _get_authenticated_user(info)
        if not user or not user.is_staff:
            raise Exception("Admin access required")

        now = timezone.now()
        today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)

        events_today = ContractEvent.objects.filter(timestamp__gte=today_start).count()
        events_total = ContractEvent.objects.count()
        active_contracts = TrackedContract.objects.filter(is_active=True).count()
        last_event = ContractEvent.objects.order_by("-timestamp").first()

        # Webhook stats for last 24h
        day_ago = now - timezone.timedelta(days=1)
        webhook_logs = WebhookDeliveryLog.objects.filter(timestamp__gte=day_ago)
        total_deliveries = webhook_logs.count()
        successful_deliveries = webhook_logs.filter(success=True).count()
        
        success_rate = (successful_deliveries / total_deliveries * 100) if total_deliveries > 0 else 100.0
        
        # Note: We don't have a delivery_time field in model, using success rate as proxy for now
        # or we could measure this if we had it. For now, returning mock or 0.
        avg_time = 0.0 

        return SystemMetrics(
            events_indexed_today=events_today,
            events_indexed_total=events_total,
            webhook_success_rate=success_rate,
            avg_webhook_delivery_time=avg_time,
            active_contracts=active_contracts,
            last_synced=last_event.timestamp if last_event else None,
            db_status="CONNECTED",
            redis_status="CONNECTED",
        )

    @strawberry.field
    def notifications(
        self,
        info: Info,
        notification_type: Optional[str] = None,
        unread_only: bool = False,
        limit: int = 50,
    ) -> list[NotificationType]:
        """Get notifications for the authenticated user (newest first, max 50)."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")

        qs = Notification.objects.filter(user=user)
        if notification_type:
            qs = qs.filter(notification_type=notification_type)
        if unread_only:
            qs = qs.filter(is_read=False)

        limit = max(1, min(limit, 50))
        return list(qs[:limit])

    @strawberry.field
    def unread_notification_count(self, info: Info) -> int:
        """Return the count of unread notifications for the authenticated user."""
        user = _get_authenticated_user(info)
        if not user:
            return 0
        return Notification.objects.filter(user=user, is_read=False).count()

    @strawberry.field
    def recent_errors(self, info: Info, limit: int = 10) -> list[ErrorLog]:
        """Get recent system errors and warnings."""
        user = _get_authenticated_user(info)
        if not user or not user.is_staff:
            raise Exception("Admin access required")

        # Using WebhookDeliveryLog failures as a source of system errors
        logs = WebhookDeliveryLog.objects.filter(success=False).order_by("-timestamp")[:limit]
        
        return [
            ErrorLog(
                id=log.id,
                timestamp=log.timestamp,
                level="ERROR",
                message=f"Webhook delivery failed: {log.error or 'Unknown error'}",
                context=f"Target: {log.subscription.target_url}"
            )
            for log in logs
        ]


@strawberry.type
class Mutation:
    @strawberry.mutation
    def register_contract(
        self,
        info: Info,
        contract_id: str,
        name: str,
        description: str = "",
        team_id: Optional[int] = None,
    ) -> ContractType:
        """Register a new contract for indexing."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")

        from .models import Team, TeamMembership

        team = None
        if team_id is not None:
            try:
                team = Team.objects.get(pk=team_id)
            except Team.DoesNotExist:
                raise Exception("Team not found")
            if not TeamMembership.objects.filter(team=team, user=user).exists():
                raise Exception("Not a member of this team")

        contract = TrackedContract.objects.create(
            contract_id=contract_id,
            name=name,
            description=description,
            owner=user,
            team=team,
        )
        return contract

    @strawberry.mutation
    def mark_notification_read(self, info: Info, notification_id: int) -> bool:
        """Mark a single notification as read."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")
        updated = Notification.objects.filter(id=notification_id, user=user).update(is_read=True)
        return updated > 0

    @strawberry.mutation
    def mark_all_notifications_read(self, info: Info) -> int:
        """Mark all notifications as read. Returns count updated."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")
        return Notification.objects.filter(user=user, is_read=False).update(is_read=True)

    @strawberry.mutation
    def clear_all_notifications(self, info: Info) -> int:
        """Delete all notifications for the user. Returns count deleted."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")
        count, _ = Notification.objects.filter(user=user).delete()
        return count

    @strawberry.mutation
    def set_contract_metadata(
        self,
        info: Info,
        contract_id: str,
        name: str,
        description: str = "",
        tags: Optional[List[str]] = None,
        documentation_url: str = "",
        github_repo: str = "",
        team_email: str = "",
    ) -> ContractMetadataType:
        """Create or update metadata for a contract."""
        from django.core.exceptions import ValidationError

        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")

        try:
            contract = TrackedContract.objects.get(contract_id=contract_id)
        except TrackedContract.DoesNotExist:
            raise Exception("Contract not found")

        instance, _ = ContractMetadata.objects.update_or_create(
            contract=contract,
            defaults={
                "name": name,
                "description": description,
                "tags": tags if tags is not None else [],
                "documentation_url": documentation_url,
                "github_repo": github_repo,
                "team_email": team_email,
            },
        )

        try:
            instance.full_clean()
        except ValidationError as exc:
            for field, messages in exc.message_dict.items():
                raise Exception(f"{field}: {messages[0]}")

        return ContractMetadataType(
            name=instance.name,
            description=instance.description,
            tags=instance.tags,
            documentation_url=instance.documentation_url,
            github_repo=instance.github_repo,
            team_email=instance.team_email,
        )

    @strawberry.mutation
    def delete_contract_metadata(self, info: Info, contract_id: str) -> bool:
        """Delete metadata for a contract. Returns False if no record exists."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")

        try:
            ContractMetadata.objects.get(contract__contract_id=contract_id).delete()
            return True
        except ContractMetadata.DoesNotExist:
            return False

    @strawberry.mutation
    def update_contract(
        self,
        info: Info,
        contract_id: str,
        name: Optional[str] = None,
        description: Optional[str] = None,
        is_active: Optional[bool] = None,
        alias: Optional[str] = None,
        event_filter_type: Optional[str] = None,
        event_filter_list: Optional[list[str]] = None,
    ) -> Optional[ContractType]:
        """Update a tracked contract."""
        user = _get_authenticated_user(info)
        if not user:
            raise Exception("Authentication required")

        try:
            contract = TrackedContract.objects.get(contract_id=contract_id)
        except TrackedContract.DoesNotExist:
            return None

        if name is not None:
            contract.name = name
        if description is not None:
            contract.description = description
        if is_active is not None:
            contract.is_active = is_active
        if alias is not None:
            contract.alias = alias
        if event_filter_type is not None:
            valid_types = {c[0] for c in TrackedContract.FILTER_TYPE_CHOICES}
            if event_filter_type not in valid_types:
                raise Exception(f"Invalid event_filter_type. Must be one of: {valid_types}")
            contract.event_filter_type = event_filter_type
        if event_filter_list is not None:
            contract.event_filter_list = event_filter_list

        contract.save()

        # Push notification when a contract is paused
        if is_active is False:
            try:
                from soroscan.ingest.services.notifications import create_and_push
                create_and_push(
                    user=contract.owner,
                    notification_type="contract_paused",
                    title="Contract Paused",
                    message=f"Indexing for contract '{contract.name}' has been paused.",
                    link=f"/contracts/{contract.contract_id}",
                )
            except Exception:
                pass

        return contract


@strawberry.type
class Subscription:
    @strawberry.subscription
    async def notifications(
        self, info: Info
    ) -> AsyncGenerator[NotificationType, None]:
        """
        Subscribe to real-time notifications for the authenticated user.
        Pushes new Notification objects as they are created.
        """
        from channels.db import database_sync_to_async

        # Resolve user from the WS scope
        scope = info.context.get("ws") if hasattr(info.context, "get") else None
        user = None
        if scope and hasattr(scope, "user"):
            user = scope.user
        if user is None:
            # Fall back to HTTP request user
            user = _get_authenticated_user(info)
        if not user or not getattr(user, "is_authenticated", False):
            return

        channel_layer = get_channel_layer()
        if not channel_layer:
            return

        channel_name = await channel_layer.new_channel()
        group_name = f"notifications_{user.pk}"
        await channel_layer.group_add(group_name, channel_name)

        try:
            while True:
                message = await channel_layer.receive(channel_name)
                notification_id = message.get("notification_id")
                if not notification_id:
                    continue

                @database_sync_to_async
                def get_notification():
                    try:
                        return Notification.objects.get(id=notification_id, user=user)
                    except Notification.DoesNotExist:
                        return None

                notification = await get_notification()
                if notification:
                    yield NotificationType(
                        id=notification.id,
                        notification_type=notification.notification_type,
                        title=notification.title,
                        message=notification.message,
                        link=notification.link,
                        is_read=notification.is_read,
                        created_at=notification.created_at,
                    )
        finally:
            await channel_layer.group_discard(group_name, channel_name)

    @strawberry.subscription
    async def contract_events(
        self, info: Info, contract_id: str
    ) -> AsyncGenerator[EventType, None]:
        """
        Subscribe to real-time events for a specific contract.
        
        Args:
            contract_id: The contract ID to subscribe to
            
        Yields:
            EventType: Real-time contract events as they occur
        """
        from channels.db import database_sync_to_async
        
        channel_layer = get_channel_layer()
        if not channel_layer:
            # If no channel layer, exit gracefully
            return
            
        channel_name = await channel_layer.new_channel()
        group_name = f"events_{contract_id}"
        
        await channel_layer.group_add(group_name, channel_name)
        
        try:
            while True:
                message = await channel_layer.receive(channel_name)
                event_data = message.get("data", {})
                
                # Create EventType from the message data
                try:
                    # Fetch the actual event from database to get proper EventType instance
                    @database_sync_to_async
                    def get_event():
                        return ContractEvent.objects.select_related("contract").get(
                            contract__contract_id=event_data.get("contract_id"),
                            ledger=event_data.get("ledger"),
                            event_index=event_data.get("event_index", 0)
                        )
                    
                    event = await get_event()
                    yield event
                except ContractEvent.DoesNotExist:
                    # If event not found, skip this message
                    continue
                except Exception:
                    # Skip any other errors and continue listening
                    continue
                    
        finally:
            await channel_layer.group_discard(group_name, channel_name)


schema = strawberry.Schema(query=Query, mutation=Mutation, subscription=Subscription)
